import { motion } from "framer-motion";
import { ScrollText } from "lucide-react";

const sections = [
  {
    number: 1,
    title: "Acceptance of Terms",
    content: `By accessing or using The Lucky Riverboat platform (the "Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Platform. These Terms constitute a legally binding agreement between you and The Lucky Riverboat. Your continued use of the Platform following any changes to these Terms constitutes acceptance of those changes.`,
  },
  {
    number: 2,
    title: "Eligibility",
    content: `You must be at least 18 years of age to use the Platform. By using the Platform, you represent and warrant that you are 18 years of age or older. You are solely responsible for ensuring that your use of the Platform complies with all applicable laws, regulations, and ordinances in your jurisdiction. Access to online gambling may be restricted or prohibited in certain jurisdictions. The Lucky Riverboat makes no representations that the Platform is legal in your jurisdiction, and we expressly disclaim any liability arising from your use of the Platform in violation of applicable local laws.`,
  },
  {
    number: 3,
    title: "Account Registration",
    content: `You may only create one (1) account per person. Multiple accounts ("multi-accounting") are strictly prohibited and will result in immediate account termination and forfeiture of any balances. When registering, you agree to provide accurate, current, and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account. The Lucky Riverboat reserves the right to verify your identity at any time.`,
  },
  {
    number: 4,
    title: "Deposits & Withdrawals",
    content: `The Lucky Riverboat accepts cryptocurrency deposits exclusively. Supported currencies include Bitcoin (BTC), Ethereum (ETH), and Tether (USDT). Fiat currency transactions are not supported. Processing times vary by network congestion: BTC transactions typically require 3 confirmations, ETH and USDT require 12 confirmations. Minimum deposit amount: $10 USD equivalent. Minimum withdrawal amount: $20 USD equivalent. Withdrawals are processed to the originating wallet address only. The Lucky Riverboat is not responsible for lost funds sent to incorrect wallet addresses. Network transaction fees are the responsibility of the user.`,
  },
  {
    number: 5,
    title: "Gaming Rules",
    content: `The Lucky Riverboat operates on a 0% house edge model with a 100% Return to Player (RTP) rate. All games are provably fair — the outcome of every bet is determined by a cryptographic algorithm that neither party can manipulate. Server seeds are hashed and committed before each bet, ensuring transparency. You may verify the fairness of any bet using our verification tools on the Provably Fair page. Any attempt to exploit game logic, abuse bonuses, or manipulate outcomes will result in account suspension. Results generated by our provably fair system are final and non-reversible.`,
  },
  {
    number: 6,
    title: "NFT Terms",
    content: `Cabin Key NFTs are digital collectibles that provide access to certain platform features and VIP benefits. Cabin Keys are not financial instruments and do not represent ownership in The Lucky Riverboat or any affiliated entity. Ownership of a Cabin Key does not guarantee any financial return or yield. The utility and benefits associated with Cabin Keys may change over time at our discretion. NFT purchases are final and non-refundable. You are responsible for the security of your wallet and private keys. The Lucky Riverboat is not responsible for lost, stolen, or inaccessible NFTs.`,
  },
  {
    number: 7,
    title: "VIP Program",
    content: `The Lucky Riverboat VIP program rewards loyal players with rakeback — a percentage return on wagered amounts calculated based on total wagering volume. VIP tiers are determined by cumulative wagering thresholds: Bronze, Silver, Gold, Platinum, Diamond, and Cabin Owner (for NFT holders). Rakeback rates increase with each tier. Rakeback accrues in real-time and may be claimed at any time. VIP benefits, tier thresholds, and rakeback rates are subject to change. The Lucky Riverboat reserves the right to modify, suspend, or terminate the VIP program at any time with reasonable notice.`,
  },
  {
    number: 8,
    title: "Prohibited Activities",
    content: `The following activities are strictly prohibited on the Platform: (a) creating multiple accounts (multi-accounting); (b) using automated software, bots, or scripts to place bets or interact with the Platform; (c) exploiting bugs, glitches, or vulnerabilities in games or the Platform; (d) abusing promotions or bonuses through coordinated play; (e) engaging in money laundering or any other illegal financial activity; (f) using the Platform for any fraudulent purpose; (g) interfering with or disrupting the Platform's infrastructure; (h) impersonating another user or Platform staff. Violations will result in permanent account termination and forfeiture of balances.`,
  },
  {
    number: 9,
    title: "Limitation of Liability",
    content: `To the maximum extent permitted by applicable law, The Lucky Riverboat and its operators, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill. The Platform is provided "as is" without warranties of any kind, express or implied. The Lucky Riverboat does not guarantee that the Platform will be uninterrupted, error-free, or secure. Your use of the Platform is at your sole risk. Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of these limitations may not apply to you.`,
  },
  {
    number: 10,
    title: "Changes to Terms",
    content: `The Lucky Riverboat reserves the right to modify these Terms at any time. We will provide notice of material changes by updating the "Last Updated" date at the top of this page and, where appropriate, by sending a notification. Your continued use of the Platform following notification of changes constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Platform immediately.`,
  },
  {
    number: 11,
    title: "Contact",
    content: `If you have any questions, concerns, or disputes regarding these Terms of Service, please contact us at support@theluckyriverboat.com. We aim to respond to all inquiries within 48 hours. For urgent matters related to account security, please mark your subject line "URGENT."`,
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-10 text-center"
      >
        <ScrollText className="w-10 h-10 text-primary mx-auto mb-4" />
        <h1
          className="text-3xl font-bold gold-text mb-2"
          style={{ fontFamily: "'Cinzel', serif" }}
          data-testid="terms-title"
        >
          Terms of Service
        </h1>
        <p className="text-muted-foreground text-sm">Last Updated: March 29, 2026</p>
      </motion.div>

      <div className="space-y-4">
        {sections.map((section, i) => (
          <motion.div
            key={section.number}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.04 }}
            className="glass-panel rounded-xl p-6"
            data-testid={`terms-section-${section.number}`}
          >
            <h2
              className="text-base font-bold text-foreground mb-3 flex items-start gap-2"
              style={{ fontFamily: "'Cinzel', serif" }}
            >
              <span className="text-primary shrink-0 tabular-nums">
                {section.number}.
              </span>
              {section.title}
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {section.content}
            </p>
          </motion.div>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="mt-8 text-center text-xs text-muted-foreground"
      >
        &copy; {new Date().getFullYear()} The Lucky Riverboat Casino &amp; Sportsbook. All rights reserved.
      </motion.div>
    </div>
  );
}
